[tool.poetry]
name = "repl_python3_beta_lightningedit"
version = "0.1.0"
description = ""
authors = ["cwi <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
fuzzywuzzy = "^0.18.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
